{
 "title": "Incident Insights",
 "tags": [
  "grafana-incident",
  "insights"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_INCIDENT", "label": "Datasource", "query": "grafana-incident-datasource" },
   {
    "name": "labels",
    "label": "Labels",
    "query": {}
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<div><img src=\"/public/plugins/grafana-irm-app/img/logo.svg\"></div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 1, "y": 0 },
   "options": {
    "content": "# Grafana Incident Insights\nSmart performance overview"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "A high-level overview of the most significant data for a quick and comprehensive view of your organization's IRM performance."
   }
  },
  {
   "title": "Total incidents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryString": "or($labels) or($severity) or(status:active status:resolved)"
    }
   ]
  },
  {
   "title": "Status of $labels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Security incidents",
   "type": "stat",
   "description": "Incidents marked with the \"security\" label are counted on this panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryString": "or($labels) or($severity) label:\"security\""
    }
   ]
  },
  {
   "title": "Mean time to resolve (MTTR)",
   "type": "stat",
   "description": "This metric represents the average duration of all incidents from start to finish",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryString": "or($labels) or($severity) or(status:active status:resolved)"
    }
   ]
  },
  {
   "title": "Total incidents by severity of $labels",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Monthly MTTR of $labels",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Daily incidents by severity of $labels",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 26 },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Monthly incidents by severity of $labels",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 26 },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "options": { "content": "# \n\n" } },
  { "title": "Response management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "Gain a better understanding of how consistently your organization follows standard incident response processes with these insights."
   }
  },
  {
   "title": "Commander assignment  of $labels",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Investigator assignment  of $labels",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Task completion for $labels",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  },
  {
   "title": "Post-Incident Report completion of $labels",
   "type": "stat",
   "description": "Incidents marked with the \"PIR\" label are counted on this panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "queryString": "or($labels) label:\"PIR\" or($severity)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }, "options": { "content": "# \n\n" } },
  { "title": "Detailed view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "Use the sorting and filtering options to analyze specific incident data and drill down into the details."
   }
  },
  {
   "title": "List of $labels incidents",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 50 },
   "targets": [
    { "queryString": "or($labels) or($severity)" }
   ]
  }
 ]
}